name: CI/CD Develop

on:
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: build
        run: |
          chmod +x "${GITHUB_WORKSPACE}/scripts/github/build.sh"
          bash ./scripts/github/build.sh

      - name: test
        run: bash ./scripts/github/test.sh
