name: CI/CD Develop

on:
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: build
        env:
          CI: false
        run: |
          git config --global user.name ${GITHUB_ACTOR}
          git config --global user.email "nasir1231011@gmail.com"
          bash ./scripts/github/build.sh

      - name: test
        run: bash ./scripts/github/test.sh
